#ifndef PDMP2_TABLES_H
#define PDMP2_TABLES_H
/* =====================================================================
 *  pdmp2_tables  --  the normative Layer II tables, in encoder form
 * ---------------------------------------------------------------------
 *  SPDX-License-Identifier: CC0-1.0
 *
 *  These are the numbers a Layer II bitstream cannot be read without:
 *  the decoder looks them up too, so they are interface, not invention.
 *  Their provenance is PROVENANCE.md -- read it before you edit this
 *  file, because "where did this number come from" is the whole reason
 *  this project exists.
 *
 *  ONE THING IS ORGANISED DIFFERENTLY FROM EVERY DECODER. A decoder
 *  reads an allocation index off the wire and looks up what it means. An
 *  encoder does the reverse: it hunts for an index to write. So the
 *  tables here are indexed the decoder's way (index -> class) but the
 *  code walks them upward, which works because in every one of these
 *  tables BOTH cost and precision rise monotonically with the index.
 *  That is a property of the tables, not an assumption about them, and
 *  tools/checktables.c proves it at build time.
 * ===================================================================== */

#include <stdint.h>

/* ---------------------------------------------------------------- *
 *  Quantisation classes.
 *
 *  A class number (`ba` below) is what an allocation index decodes to.
 *  0 means the subband is not transmitted. 2..16 are plain linear
 *  quantisers of that many bits. 17, 18 and 19 are the GROUPED classes,
 *  where three consecutive samples share one codeword because 3, 5 and
 *  9 levels do not pack into whole bits efficiently:
 *
 *      class 17:  3 levels,  3^3 = 27  in  5 bits
 *      class 18:  5 levels,  5^3 = 125 in  7 bits
 *      class 19:  9 levels,  9^3 = 729 in 10 bits
 *
 *  There is no class 1: a one-bit quantiser would be two levels, and
 *  Layer II's levels are always odd so that zero is representable.
 * ---------------------------------------------------------------- */

typedef struct {
    uint8_t  bits;     /* bits per codeword                        */
    uint8_t  group;    /* samples per codeword: 1, or 3 if grouped */
    uint16_t nlevels;  /* quantiser steps                          */
    int16_t  half;     /* added to the signed level to get the code */
} pdmp2_class_t;

#define PDMP2_CLASS_MAX 19

/* Indexed by class number; 0 and 1 are holes, kept so the class number
 * indexes directly. bits/group/nlevels/half all follow from the class,
 * so this is generated by tools/checktables.c rather than typed in --
 * see the formulas there, and the assertion that they match. */
extern pdmp2_class_t const pdmp2_classes[PDMP2_CLASS_MAX + 1];

/* Bits to send 36 subband samples (one frame's worth for one subband of
 * one channel) in this class. 0 for class 0. */
static inline int pdmp2_class_frame_bits(pdmp2_class_t const* c) {
    return c->bits == 0 ? 0 : (36 / c->group) * c->bits;
}

/* ---------------------------------------------------------------- *
 *  Bit allocation tables.
 *
 *  A band group says: the next `band_count` subbands each spend `nbal`
 *  bits on their allocation index, and that index is looked up in
 *  pdmp2_alloc_codes + `tab_offset`.
 * ---------------------------------------------------------------- */

typedef struct {
    uint8_t tab_offset;
    uint8_t nbal;
    uint8_t band_count;
} pdmp2_bandgroup_t;

/* index -> class, for every band group of every table, concatenated.
 * Layer I's group lives at 76 and is unused here; it is kept so the
 * offsets match every other implementation's and can be diffed. */
extern uint8_t const pdmp2_alloc_codes[92];

/* The three Layer II layouts. Which one applies is not a free choice --
 * the decoder derives it from the header exactly as pdmp2_pick_table()
 * does, so getting it wrong does not sound bad, it sounds like noise. */
extern pdmp2_bandgroup_t const pdmp2_groups_mpeg1[4];      /* >= 56 kbit/s/ch */
extern pdmp2_bandgroup_t const pdmp2_groups_mpeg1_low[2];  /* <  56 kbit/s/ch */
extern pdmp2_bandgroup_t const pdmp2_groups_mpeg2[3];      /* LSF, the only one */

/* ---------------------------------------------------------------- *
 *  Scalefactors (63 of them).
 *
 *  Table 3-B.1 is not a table at all, it is 2 * 2^(-b/3) evaluated 63
 *  times, so pdmp2 evaluates it instead of storing it. pdmp2_sf_a[b] is
 *  the HALF value 2^(-b/3), because that is what every formula in the
 *  encoder actually wants: it is the largest subband magnitude that
 *  scalefactor b can carry.
 * ---------------------------------------------------------------- */

#define PDMP2_SF_MAX 62  /* indices 0..62 */

extern float pdmp2_sf_a[PDMP2_SF_MAX + 1];

/* The measured 512 tap analysis prototype (src/pdmp2_window.c, generated
 * by tools/measure_window.py). Sign alternation already folded in. */
extern float const pdmp2_window[512];

void pdmp2_tables_init(void);  /* idempotent; fills what is computed */

/* Header sample-rate field: 0 = 44100/22050, 1 = 48000/24000,
 * 2 = 32000/16000. -1 if the rate is not Layer II's. */
int pdmp2_rate_index(int samplerate);
int pdmp2_is_mpeg1(int samplerate);

/* Fills *groups and returns the group count and sblimit for a config. */
int pdmp2_pick_table(int samplerate, int channels, int bitrate_kbps,
                     pdmp2_bandgroup_t const** groups, int* sblimit);

/* The 4-bit bitrate_index for the header, or -1 if this rate cannot be
 * expressed at this sample rate. */
int pdmp2_bitrate_index(int samplerate, int bitrate_kbps);

#endif /* PDMP2_TABLES_H */
