// =====================================================================
//  SynthMiner  --  folding text down to what the badge can type
//  (see fold.h; the table is generated by tools/make_fold.py)
// =====================================================================

#include "i18n/fold.h"

#include <string.h>

#include "i18n/fold_table.h"  // FOLD_TABLE, FOLD_REP_MAX

#define FOLD_TABLE_N ((int)(sizeof(FOLD_TABLE) / sizeof(FOLD_TABLE[0])))

char const* fold_utf8_next(char const* s, uint32_t* cp) {
    if (s == NULL || *s == '\0') return NULL;

    unsigned char const c = (unsigned char)*s;
    uint32_t            v;
    int                 extra;

    if (c < 0x80u) {
        *cp = c;
        return s + 1;
    } else if ((c & 0xE0u) == 0xC0u) {
        v     = c & 0x1Fu;
        extra = 1;
    } else if ((c & 0xF0u) == 0xE0u) {
        v     = c & 0x0Fu;
        extra = 2;
    } else if ((c & 0xF8u) == 0xF0u) {
        v     = c & 0x07u;
        extra = 3;
    } else {
        // A stray continuation byte or an illegal lead. Step ONE byte
        // and report the replacement character: a hand-edited lang file
        // off an SD card must walk forward, never loop (i18n.h).
        *cp = 0xFFFDu;
        return s + 1;
    }

    for (int i = 1; i <= extra; i++) {
        if (((unsigned char)s[i] & 0xC0u) != 0x80u) {  // truncated: same rule
            *cp = 0xFFFDu;
            return s + 1;
        }
        v = (v << 6) | ((uint32_t)(unsigned char)s[i] & 0x3Fu);
    }
    *cp = v;
    return s + extra + 1;
}

// The table row for `cp`, or NULL.
static fold_entry_t const* lookup(uint32_t cp) {
    if (cp > 0xFFFFu) return NULL;
    int lo = 0, hi = FOLD_TABLE_N - 1;
    while (lo <= hi) {
        int const      mid = (lo + hi) / 2;
        uint32_t const at  = FOLD_TABLE[mid].cp;
        if (at == cp) return &FOLD_TABLE[mid];
        if (at < cp) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }
    return NULL;
}

bool fold_known(uint32_t cp) {
    return cp < 0x80u || lookup(cp) != NULL;
}

void fold_text(char const* in, char* out, size_t cap) {
    if (out == NULL || cap == 0) return;
    size_t n = 0;
    out[0]   = '\0';
    if (in == NULL) return;

    uint32_t cp;
    while ((in = fold_utf8_next(in, &cp)) != NULL) {
        char const* rep;
        char        one[2];

        if (cp < 0x80u) {
            char c = (char)cp;
            if (c >= 'A' && c <= 'Z') c = (char)(c - 'A' + 'a');
            // Letters and digits only. Dropping spaces and punctuation
            // is what lets "iron pick" find "ironpickaxe".
            if (!((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9'))) continue;
            one[0] = c;
            one[1] = '\0';
            rep    = one;
        } else {
            fold_entry_t const* e = lookup(cp);
            // A character the table does not know contributes nothing
            // rather than a box. make_fold.py and worldcheck between
            // them see to it that there is no such character in any
            // string the game ships.
            if (e == NULL) continue;
            rep = e->rep;
        }

        for (char const* p = rep; *p != '\0'; p++) {
            if (n + 1 >= cap) {
                out[n] = '\0';
                return;
            }
            out[n++] = *p;
        }
    }
    out[n] = '\0';
}

bool fold_match(char const* text, char const* folded_needle) {
    if (folded_needle == NULL || folded_needle[0] == '\0') return true;
    char hay[FOLD_MAX * 2];
    fold_text(text, hay, sizeof(hay));
    return strstr(hay, folded_needle) != NULL;
}
